### ISSUE TITLE
Program Exception

### ISSUE THREAD

**Issue by arielsil** [CodingWonders/DISMTools#114]
**What is the bug about?**
Please describe the bug you're experiencing. 
:
Internal Error - invalid arg - Param: Index

- *When doing something, the program crashes*
Get-Appx Pkg info.

**How does it happen?**

Click Command / App Pkgs / Get app pkg info

**Expected behavior**

Get package info for the wim

**Additional context**

1) Happens every time
2) If I continue, the proj continues.   However, on 2nd occurance the programs errors (

System.ArgumentOutOfRangeException: InvalidArgument=Value of '-1' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListBox.ObjectCollection.RemoveAt(Int32 index)
   at DISMTools.GetAppxPkgInfoDlg.GetAppxPkgInfoDlg_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at DISMTools.MainForm.GetProvisionedAppxPackages_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: InvalidArgument=Value of '-1' is not valid for 'index'.
Parameter name: index

Error Code (HRESULT): -2146233086

Machine information:
 - Computer manufacturer: ASUS
 - Computer model: System Product Name
 - BIOS name/description: 1645 1645
 - System Management BIOS (SMBIOS) version: 1645

Operating system information:
 - OS name: Microsoft Windows Server 2025 Datacenter
 - OS version: 10.0.26085.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: 13th Gen Intel(R) Core(TM) i7-13700K
 - Processor caption: Intel64 Family 6 Model 183 Stepping 1
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 198
 - )
 - And then quits.
 - 

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

**Comment by CodingWonders** [comment]
Can you tell me more about the WIM file you're managing? Does this happen with all Windows images and installations, or just this image?

**Comment by CodingWonders** [comment]
I'm going to close this issue. Feel free to reopen it or make a new issue if you encounter the same problem.
