### ISSUE TITLE
Program Exception

### ISSUE THREAD

**Issue by thomasSTS** [CodingWonders/DISMTools#158]
I mounted an image, and cannot do anything with it, I get this error message every time:

System.NullReferenceException: Object reference not set to an instance of an object.
   at DISMTools.MainForm.UnmountImage_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: Object reference not set to an instance of an object.

Error Code (HRESULT): 80004003

Machine information:
 - Computer manufacturer: SAMSUNG ELECTRONICS CO., LTD.
 - Computer model: 960XGL
 - BIOS name/description: P06ALX.350.240527.04 P06ALX.350.240527.04
 - System Management BIOS (SMBIOS) version: P06ALX.350.240527.04

Operating system information:
 - OS name: Microsoft Windows 11 Pro for Workstations
 - OS version: 10.0.26120.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: Intel(R) Core(TM) Ultra 9 185H
 - Processor caption: Intel64 Family 6 Model 170 Stepping 4
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 1
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.

**Comment by CodingWonders** [comment]
@thomasSTS, sorry for replying to you so late. Have you been able to fix this with the latest releases?
