### ISSUE TITLE
Getting Program exception on Get Information

### ISSUE THREAD

**Issue by ehsan18t** [CodingWonders/DISMTools#186]
If I try to use `Get Information` (eg: `get driver information`) for any section I get this kind of error. I tried both stable and preview build with both installer and portable option.

**Exception information**: 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DISMTools.GetPkgInfoDlg.GetPkgInfoDlg_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: Object reference not set to an instance of an object.

Error Code (HRESULT): 80004003

Program information:
 - DISMTools Version: 0.6.0.24102
 - Preview release? Yes
 - Branch: dt_preview
 - Build time: 241025-1603
Information about the image loaded in this project:
 - Image name: Windows 11 IoT Enterprise LTSC
 - Image description: Windows 11 IoT Enterprise LTSC
 - Image version: 10.0.26100.1742
Machine information:
 - Computer manufacturer: Micro-Star International Co., Ltd.
 - Computer model: MS-7D75
 - BIOS name/description: 1.J0 1.J0
 - System Management BIOS (SMBIOS) version: 1.J0

Operating system information:
 - OS name: Microsoft Windows 11 IoT Enterprise Subscription LTSC
 - OS version: 10.0.26100.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: AMD Ryzen 5 8600G w/ Radeon 760M Graphics      
 - Processor caption: AMD64 Family 25 Model 117 Stepping 2
 - Processor manufacturer: AuthenticAMD
 - Processor family (WMI type): 107
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.
```

**How did it happen?**
 - Mount the image.
 - Click `get driver information`

**Comment by CodingWonders** [comment]
@ehsan18t, this can happen if there's an error when getting this information with the background processes.

When that happens, an API error dialog will appear (in the background, but will make a system sound). Could you try loading the project with that image mounted and see if that dialog appears?

**Comment by CodingWonders** [comment]
Closed due to inactivity
