### ISSUE TITLE
Program exception

### ISSUE THREAD

**Issue by l33m4n** [CodingWonders/DISMTools#188]
**PLEASE PROVIDE DETAILS ABOUT THE EXCEPTION, OR YOUR ISSUE WILL BE CLOSED WITHIN 4 HOURS**

**Exception information**: please tell us what happened below:

System.NullReferenceException: Object reference not set to an instance of an object.
   at DISMTools.MainForm.DetectVersions(FileVersionInfo DismVer, Version NTVer)
   at DISMTools.Options.ApplyProgSettings()
   at DISMTools.Options.OK_Button_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: Object reference not set to an instance of an object.

Error Code (HRESULT): 80004003

Program information:
 - DISMTools Version: 0.6.0.24111
 - Preview release? Yes
 - Branch: dt_preview
 - Build time: 241108-2001
Information about the image loaded in this project:
 - Image name: imgName
 - Image description: imgDesc
 - Image version: imgVersion
Machine information:
 - Computer manufacturer: ASUS
 - Computer model: System Product Name
 - BIOS name/description: 3403 3403
 - System Management BIOS (SMBIOS) version: 3403

Operating system information:
 - OS name: Microsoft Windows 11 Home
 - OS version: 10.0.22000.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: 12th Gen Intel(R) Core(TM) i5-12600K
 - Processor caption: Intel64 Family 6 Model 151 Stepping 2
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 205
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.

This information has been copied to the clipboard.

**How did it happen?** What steps did you perform in order to experience this problem?

Had a image loaded, then selected scratch directories then configure scratch directories then -> ok prompts this error. I am unsure if this is user error or not, but as the program requests me to make a bug report, here i am

**Comment by CodingWonders** [comment]
@l33m4n, since this happens when clicking OK in the settings dialog, could you give me your settings file? It's in `<program directory>\settings.ini`
