### ISSUE TITLE
Program exception

### ISSUE THREAD

**Issue by prajwalpatil2204** [CodingWonders/DISMTools#198]
If you have run into an internal error (program exception), we would like to learn more about it. When an error occurs, its information will be copied to your clipboard. If you can't find error information on your clipboard, a local copy was also saved at `<program directory>\Logs\Errors`.

**PLEASE PROVIDE DETAILS ABOUT THE EXCEPTION, OR YOUR ISSUE WILL BE CLOSED WITHIN 4 HOURS**

**Exception information**: please tell us what happened below:

System.NullReferenceException: Object reference not set to an instance of an object.
   at DISMTools.GetPkgInfoDlg.GetPkgInfoDlg_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: Object reference not set to an instance of an object.

Error Code (HRESULT): 80004003

Program information:
 - DISMTools Version: 0.5.1.24112
 - Preview release? No
 - Branch: stable
 - Build time: 241122-1520
 - Portable copy? Yes

Information about the image loaded in this project:
 - Image name: Windows 10 Pro
 - Image description: Windows 10 Pro
 - Image version: 10.0.19045.5198
Machine information:
 - Computer manufacturer: Dell Inc.
 - Computer model: Inspiron 3542
 - BIOS name/description: A16 A16
 - System Management BIOS (SMBIOS) version: A16

Operating system information:
 - OS name: Microsoft Windows 10 Pro
 - OS version: 10.0.19045.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
 - Processor caption: Intel64 Family 6 Model 69 Stepping 1
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 206
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

[DT-Error-25 November 2024 09-53-51 PM.log](https://github.com/user-attachments/files/17905936/DT-Error-25.November.2024.09-53-51.PM.log)

**Comment by CodingWonders** [comment]
Closed due to inactivity
