### ISSUE TITLE
Program exception

### ISSUE THREAD

**Issue by yyg1208** [CodingWonders/DISMTools#200]
System.IO.IOException: The specified file could not be encrypted.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DISMTools.MainForm.GetPackageDisplayName(String PackageName, String DisplayName)
   at DISMTools.GetAppxPkgInfoDlg.ListBox1_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: The specified file could not be encrypted.

Error Code (HRESULT): 80071770

Program information:
 - DISMTools Version: 0.5.1.24112
 - Preview release? No
 - Branch: stable
 - Build time: 241122-1520
 - Portable copy? Yes

Machine information:
 - Computer manufacturer: Micro-Star International Co., Ltd.
 - Computer model: Stealth 16Studio A13VF
 - BIOS name/description: E15F2IMS.10E E15F2IMS.10E
 - System Management BIOS (SMBIOS) version: E15F2IMS.10E

Operating system information:
 - OS name: Microsoft Windows 11 IoT Enterprise LTSC
 - OS version: 10.0.26100.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: 13th Gen Intel(R) Core(TM) i9-13900H
 - Processor caption: Intel64 Family 6 Model 186 Stepping 2
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 207
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.
**How did it happen?** What steps did you perform in order to experience this problem?
This exception occurs when you click "Get AppX Package information" and select the "Intel Graphics Experience" app.

**Comment by CodingWonders** [comment]
This issue will be closed, as it will continue in #199
