### ISSUE TITLE
Program exception

### ISSUE THREAD

**Issue by Oldsch00lpunk** [CodingWonders/DISMTools#201]
System.IO.FileNotFoundException: H:\WinNTSetup\Base\DISMTools\Mount\Windows\system32\ntoskrnl.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at DISMTools.MainForm.DetectMountedImages(Boolean DebugLog)
   at DISMTools.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: H:\WinNTSetup\Base\DISMTools\Mount\Windows\system32\ntoskrnl.exe

Error Code (HRESULT): 80070002

Program information:
 - DISMTools Version: 0.6.0.24121
 - Preview release? Yes
 - Branch: dt_preview
 - Build time: 241205-1241
 - Portable copy? No

Machine information:
 - Computer manufacturer: Dell Inc.
 - Computer model: Inspiron 3583
 - BIOS name/description: 1.30.0 1.30.0
 - System Management BIOS (SMBIOS) version: 1.30.0

Operating system information:
 - OS name: Microsoft Windows 11 Pro
 - OS version: 10.0.26120.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
 - Processor caption: Intel64 Family 6 Model 142 Stepping 11
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 198
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.

**Comment by CodingWonders** [comment]
@Oldsch00lpunk, judging by the mount path, have you used WinNTSetup?
