### ISSUE TITLE
Program exception

### ISSUE THREAD

**Issue by Dretreyt** [CodingWonders/DISMTools#205]
If you have run into an internal error (program exception), we would like to learn more about it. When an error occurs, its information will be copied to your clipboard. If you can't find error information on your clipboard, a local copy was also saved at `<program directory>\Logs\Errors`.

**PLEASE PROVIDE DETAILS ABOUT THE EXCEPTION, OR YOUR ISSUE WILL BE CLOSED WITHIN 4 HOURS**

**Exception information**: please tell us what happened below:

**How did it happen?** What steps did you perform in order to experience this problem?

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at DISMTools.MainForm.SaveDTSettings()
   at DISMTools.MainForm.MainForm_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: Value cannot be null.
Parameter name: value

Error Code (HRESULT): 80004003

Program information:
 - DISMTools Version: 0.5.1.24102
 - Preview release? No
 - Branch: stable
 - Build time: 241026-0957
Machine information:
 - Computer manufacturer: HP
 - Computer model: HP EliteBook 850 G5
 - BIOS name/description: Q78 Ver. 01.25.00 Q78 Ver. 01.25.00
 - System Management BIOS (SMBIOS) version: Q78 Ver. 01.25.00

Operating system information:
 - OS name: Microsoft Windows 10 Enterprise
 - OS version: 10.0.19045.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
 - Processor caption: Intel64 Family 6 Model 142 Stepping 10
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 198
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.

This information has been copied to the clipboard.

**Comment by Dretreyt** [comment]
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at DISMTools.MainForm.SaveDTSettings()
   at DISMTools.MainForm.MainForm_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: Value cannot be null.
Parameter name: value

Error Code (HRESULT): 80004003

Program information:
 - DISMTools Version: 0.5.1.24102
 - Preview release? No
 - Branch: stable
 - Build time: 241026-0957
Machine information:
 - Computer manufacturer: HP
 - Computer model: HP EliteBook 850 G5
 - BIOS name/description: Q78 Ver. 01.25.00 Q78 Ver. 01.25.00
 - System Management BIOS (SMBIOS) version: Q78 Ver. 01.25.00

Operating system information:
 - OS name: Microsoft Windows 10 Enterprise
 - OS version: 10.0.19045.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
 - Processor caption: Intel64 Family 6 Model 142 Stepping 10
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 198
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.

This information has been copied to the clipboard.

**Comment by CodingWonders** [comment]
First, could you update your copy of DISMTools to the latest version? This could help fix the problem
