### ISSUE TITLE
Program exception

### ISSUE THREAD

**Issue by arielsil** [CodingWonders/DISMTools#206]
If you have run into an internal error (program exception), we would like to learn more about it. When an error occurs, its information will be copied to your clipboard. If you can't find error information on your clipboard, a local copy was also saved at `<program directory>\Logs\Errors`.

**PLEASE PROVIDE DETAILS ABOUT THE EXCEPTION, OR YOUR ISSUE WILL BE CLOSED WITHIN 4 HOURS**

**Exception information**: please tell us what happened below:

System.IO.FileNotFoundException: \Windows\system32\ntoskrnl.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at DISMTools.MainForm.IsWindows8OrHigher(String NTKeExe)
   at DISMTools.ImgInfoSaveDlg.GetAppxInformation()
   at DISMTools.ImgInfoSaveDlg.ImgInfoSaveDlg_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: \Windows\system32\ntoskrnl.exe

Error Code (HRESULT): 80070002

Program information:
 - DISMTools Version: 0.6.0.24122
 - Preview release? No
 - Branch: stable
 - Build time: 241220-1044
 - Portable copy? Yes

Machine information:
 - Computer manufacturer: ASUS
 - Computer model: System Product Name
 - BIOS name/description: 1805 1805
 - System Management BIOS (SMBIOS) version: 1805

Operating system information:
 - OS name: Microsoft Windows Server 2025 Datacenter
 - OS version: 10.0.26334.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: 13th Gen Intel(R) Core(TM) i7-13700K
 - Processor caption: Intel64 Family 6 Model 183 Stepping 1
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 198
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.

This information has been copied to the clipboard.

**How did it happen?** What steps did you perform in order to experience this problem?

**Comment by CodingWonders** [comment]
@arielsil, thanks for reporting this issue. It will be fixed on the first preview release of DISMTools 0.6.1, expected to come out in mid-January.
